services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petitions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx drizzle-kit push && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: