import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Home() {
    if (metadata.title) {
        return true;
    }
    return (
        <h1>Hello World</h1>
    );
}
